# Generated by Django 3.0.4 on 2021-07-23 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='bio',
            field=models.TextField(blank=True, default='bio'),
        ),
        migrations.AlterField(
            model_name='info',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
