# Generated by Django 3.0.4 on 2021-07-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0004_socialacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialacc',
            name='phone_no',
            field=models.IntegerField(blank=True),
        ),
    ]
