# Generated by Django 3.0.4 on 2021-09-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0009_auto_20210902_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialacc',
            name='phone_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
