# Generated by Django 3.0.4 on 2021-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0012_locationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='accuracy',
            field=models.FloatField(),
        ),
    ]
