# Generated by Django 3.0.4 on 2021-09-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0014_auto_20210909_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
