# Generated by Django 3.0.4 on 2021-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0017_locationdata_location_sharing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
