# Generated by Django 3.0.4 on 2022-06-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0018_auto_20211112_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='profile_emoji',
            field=models.TextField(default='😊'),
        ),
    ]
