# Generated by Django 3.0.4 on 2022-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0019_info_profile_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialacc',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialacc',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
