# Generated by Django 3.0.4 on 2022-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0020_auto_20220605_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date_regitser', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
