# Generated by Django 3.0.4 on 2022-06-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0022_accountsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='eventNotifications',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='on', max_length=3),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='insights',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='on', max_length=3),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='mehCard',
            field=models.CharField(choices=[('off', 'off'), ('on', 'on')], default='on', max_length=3),
        ),
    ]
