# Generated by Django 3.0.4 on 2023-05-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0023_auto_20220623_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='security_ans',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='security_q',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
