# Generated by Django 3.0.4 on 2023-06-12 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersData', '0024_auto_20230520_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField()),
                ('business_type', models.CharField(max_length=255)),
                ('business_location', models.CharField(max_length=255)),
                ('business_website', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='business_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('start_time', models.CharField(default='10:00 AM', max_length=10)),
                ('end_time', models.CharField(default='12:00 PM', max_length=10)),
                ('map_range', models.IntegerField(default=50)),
                ('location', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('sale', 'sale'), ('offer', 'offer'), ('open', 'open'), ('closed', 'closed'), ('other', 'other')], default='public', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
