# Generated by Django 3.0.4 on 2023-06-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0025_auto_20230612_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='business_linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersData.BusinessDetails'),
        ),
    ]
