# Generated by Django 3.0.4 on 2023-06-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersData', '0026_info_business_linked_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='location',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='events',
            name='longitude',
            field=models.CharField(default=0.0, max_length=255),
        ),
    ]
